# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal website of Franci Rrapi.'
    # twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
# header:
#   navbar:
#     enable: true
#     blox: floating-theme-toggler

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    highlight_active_link: true
    # -------------------------------------------
    logo:
      text: ""
      filename: "assets/media/logo.png" # in `assets/media/` folder
    # button: # call to action button, top right
    #   enable: true
    #   text: "test text"
    #   url: "#"

# Site footer
footer:
  copyright:
    notice: '© {year} Franci Rrapi. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
